name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  typecheck:
    name: ğŸ§ª typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: oven-sh/setup-bun
      - run: bun run typecheck
  lint:
    name: ğŸ§ª lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: oven-sh/setup-bun
      - run: bun run lint
